export type OdataWarehouseImportType = {
  __metadata: {
    uri: string
    type: string
  }
  CCONF_ID: string
  CCONF_UNIT: string
  CCR_IDENT_UUID: string
  CINC_CLASS_CD: string
  CINC_TRANS_LOC: string
  CINV_TYPE: string
  CINV_UNIT: string
  CLOCATION_UUID: string
  CLOG_AREA_UUID: string
  CLOG_CONF_TYPE: string
  CMATERIAL_UUID: string
  CMOVE_DIRECTION: string
  CNET_PRC_AMT_CUR: string
  CPRODUCT_CAT_INT_ID_STRG: string
  CPURCHASING_UNIT: string
  CREF_ID: string
  CREF_MST_ID: string
  CREF_MST_IT_ID: string
  CREF_SLR_ID: string
  CSCRAP_UNIT: string
  CSELLER: string
  CTA_DATE: string
  CTA_DATE_TIME: string
  FCCONF_QUAN: string
  FCINV_QUAN_NORM: string
  FCNET_PRC_AMT: string
  FCZ0COUNT: string
  FCZ7B2C3FDBA947C92EC4F382: string
  KCCONF_QUAN: string
  KCINV_QUAN_NORM: string
  KCNET_PRC_AMT: string
  KCZ0COUNT: string
  KCZ7B2C3FDBA947C92EC4F382: string
  RCNET_PRC_AMT: string
  RCZ7B2C3FDBA947C92EC4F382: string
  TCONF_UNIT: string
  TCR_IDENT_UUID: string
  TINC_CLASS_CD: string
  TINV_TYPE: string
  TINV_UNIT: string
  TLOCATION_UUID: string
  TLOG_AREA_UUID: string
  TLOG_CONF_TYPE: string
  TMATERIAL_UUID: string
  TMOVE_DIRECTION: string
  TNET_PRC_AMT_CUR: string
  TPURCHASING_UNIT: string
  TSCRAP_UNIT: string
  TSELLER: string
  UCCONF_QUAN: string
  UCINV_QUAN_NORM: string
  UCZ7B2C3FDBA947C92EC4F382: string
}
