import { registerAs } from '@nestjs/config'

export const OdataWarehouseImportConfig = registerAs(
  'odata_warehouse_import',
  () => ({
    username: process.env.SAP_USERNAME || 'AE-0000002',
    password: process.env.SAP_PASSWORD || 'Snp12345678',
    warehouseImportUri:
      process.env.SAP_WAREHOUSE_IMPORT_URI ||
      'https://my350617.sapbydesign.com/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ135F05FDAFE0A9957E72B8QueryResults?%24inlinecount=allpages&%24select=CTA_DATE%2CCTA_DATE_TIME%2CCCONF_ID%2CCLOG_CONF_TYPE%2CTLOG_CONF_TYPE%2CCINV_UNIT%2CTINV_UNIT%2CFCCONF_QUAN%2CUCCONF_QUAN%2CCCONF_UNIT%2CTCONF_UNIT%2CFCZ0COUNT%2CCCR_IDENT_UUID%2CTCR_IDENT_UUID%2CFCINV_QUAN_NORM%2CUCINV_QUAN_NORM%2CCINC_CLASS_CD%2CCINC_TRANS_LOC%2CTINC_CLASS_CD%2CCLOG_AREA_UUID%2CTLOG_AREA_UUID%2CRCZ7B2C3FDBA947C92EC4F382%2CFCZ7B2C3FDBA947C92EC4F382%2CUCZ7B2C3FDBA947C92EC4F382%2CCMOVE_DIRECTION%2CTMOVE_DIRECTION%2CRCNET_PRC_AMT%2CCNET_PRC_AMT_CUR%2CTNET_PRC_AMT_CUR%2CFCNET_PRC_AMT%2CCREF_MST_ID%2CCREF_MST_IT_ID%2CCMATERIAL_UUID%2CTMATERIAL_UUID%2CCPURCHASING_UNIT%2CTPURCHASING_UNIT%2CCREF_ID%2CCREF_SLR_ID%2CCINV_TYPE%2CTINV_TYPE%2CCPRODUCT_CAT_INT_ID_STRG%2CCLOCATION_UUID%2CTLOCATION_UUID%2CCSELLER%2CTSELLER%2CCSCRAP_UNIT%2CTSCRAP_UNIT%2CKCCONF_QUAN%2CKCZ0COUNT%2CKCINV_QUAN_NORM%2CKCZ7B2C3FDBA947C92EC4F382%2CKCNET_PRC_AMT',
  })
)

export const SAP_WAREHOUSE_IMPORT_INTERVAL =
  Number(process.env.SAP_WAREHOUSE_IMPORT_INTERVAL) || 30 * 60 * 1000

export const SAP_WAREHOUSE_IMPORT_RETRY_NUMBER =
  Number(process.env.SAP_WAREHOUSE_IMPORT_RETRY_NUMBER) || 5
export const SAP_WAREHOUSE_IMPORT_RETRY_EACH_TIME =
  Number(process.env.SAP_WAREHOUSE_IMPORT_RETRY_EACH_TIME) || 5000
