# docker compose version
version: '3.8'
# all the containers have to declare inside services
services:
  purchased-order-service:
    container_name: ${CONTAINER_NAME}
    image: purchased-order-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      mesx-net:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    ports:
      - ${APP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
networks:
  mesx-net:
    name: ${MESX_NET_NAME}
    external: true
