version: '3.8'
name: smc_project

services:
  purchase_order_service:
    container_name: smc_purchase_order_service_local
    image: smc_purchase_order_service_image
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    networks:
      mesx_network:
        ipv4_address: ${CONTAINER_NETWORK_IP}
    restart: unless-stopped
    volumes:
      - .:/app
      - smc_purchase_order_node_modules:/app/node_modules/
    command: npm run start:debug
    ports:
      - ${APP_CONTAINER_PORT}:${SERVER_HTTP_PORT}
      - 9261:9261

networks:
  mesx_network:
    name: ${MESX_NET_NAME}
    external: true

volumes:
  smc_purchase_order_node_modules:
