import { NatsService } from '@config/nats.config';

export const MESSAGE_PATTERN = {
  SALE: {
    LIST_VENDOR_BY_IDS: `${NatsService.SALE}.get_vendor_by_ids`,
    DETAIL: `${NatsService.SALE}.get_vendor`,
    LIST_REASON_BY_IDS: `${NatsService.SALE}.get_reason_by_ids`,
    REASON_DETAIL: `${NatsService.SALE}.get_reason_detail`,
    LIST_VENDOR: `${NatsService.SALE}.get_vendor_list`,
  },
  PRODUCING: {
    LIST_PLANT: `${NatsService.PRODUCE}.plant_list`,
    DETAIL_PLANT: `${NatsService.PRODUCE}.plant_detail`,
    DETAIL_PRODUCTION_LINE: `${NatsService.PRODUCE}.production_line_detail`,
    LIST_PRODUCTION_LINE: `${NatsService.PRODUCE}.production_line_list`,
    LIST_PRODUCTION_LINE_BY_IDS: `${NatsService.PRODUCE}.get_production_line_by_ids`,
    LIST_PLANT_BY_CONDITIONS: `${NatsService.PRODUCE}.plant_list_by_conditions`,
    LIST_PLANT_FLOOR_BY_IDS: `${NatsService.PRODUCE}.plant_floor_list_by_ids`,
    LIST_PLANT_FLOOR_BY_CONDITIONS: `${NatsService.PRODUCE}.plant_floor_list_by_conditions`,
    DETAIL_ERROR_CODE: `${NatsService.PRODUCE}.error_code_detail`,
    LIST_ERROR_CODE_BY_CONDITIONS: `${NatsService.PRODUCE}.error_code_list_by_conditions`,
    PRODUCING_STEP_LIST_BY_CONDITIONS: `${NatsService.PRODUCE}.get_producing_step_by_conditions`,
  },
  ITEM: {
    LIST_UNIT_SETTING: `${NatsService.ITEM}.get_list_item_unit_setting`,
    DETAIL_UNIT_SETTING: `${NatsService.ITEM}.get_item_unit_setting_detail`,
    LIST_COUNTRY_BY_IDS: `${NatsService.ITEM}.get_manufacturing_country_by_ids`,
    LIST_COUNTRY: `${NatsService.ITEM}.get_manufacturing_country_list`,
    DETAIL_COUNTRY: `${NatsService.ITEM}.manufacturing_country_detail`,
    LIST_ITEM_BY_IDS: `${NatsService.ITEM}.get_items_by_ids`,
    ITEM_STOCKS_AVAILABLE: `${NatsService.ITEM}.item_stocks_available`,
    ITEM_LIST_BY_CODES: `${NatsService.ITEM}.get_item_by_codes`,
  },
  COST_CENTER: {
    LIST_COST_CENTER_BY_CONDITIONS: `${NatsService.COST_CENTER}.get_cost_center_by_conditions`,
    LIST_COST_CENTER: `${NatsService.COST_CENTER}.get_cost_center_list`,
    DETAIL_COST_CENTER: `${NatsService.COST_CENTER}.cost_center_detail`,
    GET_BY_CONDITIONS: `${NatsService.COST_CENTER}.get_cost_center_by_conditions`,
  },
  USER: {
    FIND: `${NatsService.USER}.find`,
    INSERT_PERMISSION: `${NatsService.USER}.insert_permission`,
    DELETE_PERMISSION_NOT_ACTIVE: `${NatsService.USER}.delete_permission_not_active`,
    LIST_FACTORY: `${NatsService.USER}.list_factories`,
    DETAIL_FACTORY: `${NatsService.USER}.detail_factory`,
    DETAIL_COMPANY: `${NatsService.USER}.company_detail`,
    DETAIL_USER: `${NatsService.USER}.detail`,
    LIST_USER: `${NatsService.USER}.list`,
    SYNC_FACTORY: `${NatsService.USER}.sync_factories`,
    DETAIL_DEPARTMENT_SETTING: `${NatsService.USER}.department_setting_detail`,
    LIST_DEPARTMENT_SETTING: `${NatsService.USER}.department_setting_list`,
    LIST_DEPARTMENT_SETTING_BY_IDS: `${NatsService.USER}.get_department_setting_by_ids`,
    LIST_USER_BY_IDS: `${NatsService.USER}.get_users_by_ids`,
  },
};
