import {
  ATTRIBUTE_GROUP_PERMISSION,
  ATTRIBUTE_GROUP_TEMPLATE_PERMISSION,
} from './attribute-group.permission';
import {
  ATTRIBUTE_PERMISSION,
  ATTRIBUTE_TEMPLATE_PERMISSION,
} from './attribute.permission';
import {
  EXPORT_PLAN_PERMISSION,
  EXPORT_PLAN_TEMPLATE_PERMISSION,
} from './export-plan.permission';
import {
  TEMPLATE_GROUP_PERMISSION,
  TEMPLATE_PERMISSION,
} from './template.permission';
import { UNIT_GROUP_PERMISSION, UNIT_PERMISSION } from './unit';

export const PERMISSION = [
  ...UNIT_PERMISSION,
  ...ATTRIBUTE_GROUP_PERMISSION,
  ...ATTRIBUTE_PERMISSION,
  ...TEMPLATE_PERMISSION,
  ...EXPORT_PLAN_PERMISSION,
];

export const GROUP_PERMISSION = [
  UNIT_GROUP_PERMISSION,
  ATTRIBUTE_GROUP_TEMPLATE_PERMISSION,
  ATTRIBUTE_TEMPLATE_PERMISSION,
  TEMPLATE_GROUP_PERMISSION,
  EXPORT_PLAN_TEMPLATE_PERMISSION,
];

export const INSERT_PERMISSION = {
  permission: PERMISSION,
  groupPermission: GROUP_PERMISSION,
};
